USE CUST_DB
ALTER DATABASE CUST_DB
ADD FILE (NAME=Cust_DB1, FILENAME='C:\ProgramFiles\Microsofl SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\CUST_DB1.ndf')
TO FILEGROUP FG_ReadOnly
ALTER DATABASE CUST_DB
MODIFY FILEGROUP FG_ReadOnly DEFAULT